name:Ilk Devops Robotum

on:
  push:
    banches:
      -main

jops:
  sistem-kontrol:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Karargahtan Çek
        uses: actions/checkout@v4
      -name: Terminale Mesaj Yazdır
        run: echo "Yeni bir kod eklendi veya değiştirildi Haberin olsun"
      -name:Proje Dosyalarını Listele
        run: ls -la
  